# Languages
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  locale: en-us
  languageName: English
  weight: 1
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Research
        url: /publication/
        weight: 20
      - name: CV
        url: /cv/
        weight: 30

fr:
  locale: fr-fr
  languageName: Français
  weight: 2
  menu:
    main:
      - name: Accueil
        url: /fr/
        weight: 10
      - name: Recherche
        url: /fr/publication/
        weight: 20
      - name: CV
        url: /fr/cv/
        weight: 30
